CREATE TABLE IF NOT EXISTS sys_admin_user (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE COMMENT '登录账号',
  password VARCHAR(100) NOT NULL COMMENT 'BCrypt密码',
  nickname VARCHAR(50) DEFAULT NULL,
  phone VARCHAR(20) DEFAULT NULL,
  email VARCHAR(100) DEFAULT NULL,
  gender VARCHAR(10) DEFAULT 'unknown',
  avatar VARCHAR(255) DEFAULT NULL,
  role_name VARCHAR(50) DEFAULT '管理员',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='后台管理员';

CREATE TABLE IF NOT EXISTS dashboard_daily_metric (
  stat_date DATE NOT NULL PRIMARY KEY,
  order_count INT NOT NULL DEFAULT 0,
  new_user_count INT NOT NULL DEFAULT 0,
  pending_payment_count INT NOT NULL DEFAULT 0,
  sales_amount DECIMAL(14, 2) NOT NULL DEFAULT 0,
  yesterday_sales_amount DECIMAL(14, 2) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='首页日指标';

CREATE TABLE IF NOT EXISTS dashboard_pending_task (
  task_key VARCHAR(50) NOT NULL PRIMARY KEY,
  label VARCHAR(100) NOT NULL,
  count_value INT NOT NULL DEFAULT 0,
  sort_num INT NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='待处理事务计数';

CREATE TABLE IF NOT EXISTS pms_category (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(50) NOT NULL UNIQUE,
  name VARCHAR(100) NOT NULL,
  parent_id BIGINT NOT NULL DEFAULT 0,
  level_num INT NOT NULL DEFAULT 1,
  product_count INT NOT NULL DEFAULT 0,
  unit VARCHAR(20) DEFAULT '件',
  visible BOOLEAN NOT NULL DEFAULT TRUE,
  sort_num INT NOT NULL DEFAULT 0,
  deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS pms_brand (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(50) NOT NULL UNIQUE,
  name VARCHAR(100) NOT NULL,
  initial_char VARCHAR(5),
  product_count INT NOT NULL DEFAULT 0,
  supplier VARCHAR(50),
  visible BOOLEAN NOT NULL DEFAULT TRUE,
  sort_num INT NOT NULL DEFAULT 0,
  deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS pms_product (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  product_no VARCHAR(20) NOT NULL UNIQUE,
  title VARCHAR(200) NOT NULL,
  subtitle VARCHAR(200),
  thumb VARCHAR(500),
  original_price DECIMAL(10, 2) NOT NULL DEFAULT 0,
  discount_price DECIMAL(10, 2) NOT NULL DEFAULT 0,
  status VARCHAR(10) NOT NULL DEFAULT 'off',
  audit_status VARCHAR(20) NOT NULL DEFAULT 'pending',
  remark VARCHAR(500),
  sku VARCHAR(50),
  sort_num INT NOT NULL DEFAULT 0,
  stock INT NOT NULL DEFAULT 0,
  month_sales INT NOT NULL DEFAULT 0,
  total_sales INT NOT NULL DEFAULT 0,
  supplier VARCHAR(50),
  category_code VARCHAR(50),
  brand_code VARCHAR(50),
  deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS pms_product_comment (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  product_no VARCHAR(20) NOT NULL,
  rating VARCHAR(10) NOT NULL,
  content VARCHAR(1000),
  featured BOOLEAN NOT NULL DEFAULT FALSE,
  deleted BOOLEAN NOT NULL DEFAULT FALSE
);
